/** Service identity — used in logs, /health and the OpenAPI document. */

export const SERVICE_NAME = "jan-arogya-api";
export const SERVICE_VERSION = "0.1.0";

export const API_TITLE = "Jan Arogya Portal API";
export const API_DESCRIPTION = [
  "REST API of the Jan Arogya Portal (JAP) — a consent-aware healthcare",
  "coordination platform built on the Ayushman Bharat Digital Mission (ABDM)",
  "ecosystem.",
  "",
  "**Authentication (Phase 3)** — role-scoped alias resolution",
  "(HPID / username / mobile; ABHA number / address), case/space/dash-",
  "insensitive matching, discriminated session contract, and HttpOnly",
  "SameSite=Lax cookie sessions.",
  "",
  "**Patients (Phase 4)** — POST/GET/PATCH under `/api/v1/patients`",
  "with JAP-internal opaque patient ids, external identifiers mapped exclusively",
  "through `patient_identities` (ABHA number / address, canonicalized and",
  "masked, verification state server-owned), and an explicit",
  "provisional → registered lifecycle. ABHA is never mandatory for healthcare",
  "delivery and is never conflated with authentication or consent.",
  "",
  "**Authorization (Phase 4)** — every request runs",
  "session → role capability → data-level access → audit. Roles are",
  "default-deny against an explicit capability matrix; patient records are",
  "scoped to the tenant that registered them, with cross-tenant reads opened",
  "only by an active consent artifact and cross-tenant writes never opened at",
  "all. Denials answer 403 with the `AccessDecision` reason and write a",
  "`blocked` audit row; a record outside the caller's scope is absent from",
  "search rather than merely sealed.",
  "",
  "**Clinical records (Phase 5)** — encounters and append-only clinical",
  "records per patient: history is added to, never rewritten.",
  "",
  "**Consents (Phase 6)** — the consent plane: a clinician requests,",
  "only the patient approves, rejects or revokes, and expiry is evaluated on",
  "read. Consent state lives here and nowhere else; the patient-registry",
  "decision reads it through `services/consent-view.ts`.",
  "",
  "**Access decisions (Phase 7)** — `POST /api/v1/access/evaluate`",
  "answers the purpose- and record-type-scoped sharing question. It speaks the",
  "same closed reason vocabulary as the patient-registry decision",
  "(`same_tenant`, `consent_active`, `self`, `platform`, `no_consent`,",
  "`consent_pending`, `consent_expired`, `consent_revoked`, `consent_denied`,",
  "`role_not_permitted`), with a `detail` field for the refinement a shared",
  "vocabulary folds together — so a denial means the same thing whichever",
  "endpoint reported it. The two questions stay distinct: tenancy opens a",
  "record, consent scopes a purpose.",
  "",
  "**Audit (Phase 8)** — one append-only, hash-chained trail for every",
  "sensitive action, allowed and denied: each event hashes a canonical envelope",
  "that includes the actor snapshot, the decision `reason` and the `capability`",
  "checked, so rewriting why an access happened breaks the chain. Entries carry",
  "ids and reasons, never names, dates of birth, identifier values or search",
  "terms.",
  "",
  "Design constraints carried by every endpoint:",
  "medical records stay off-chain; JAP never becomes a centralized national",
  "medical-record database; every sensitive action is written to a",
  "tamper-evident, hash-chained audit trail.",
].join("\n");
